export const candidates = [
  {
    id: 1,
    name: "John Doe",
    email: "john.doe@example.com",
    status: "approved",
    interviewStatus: "scheduled",
    assignedInterviewer: "Sarah Wilson",
    profilePhoto:
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face",
    personalDetails: {
      firstName: "John",
      lastName: "Doe",
      mobileNo: "+1-555-0123",
      email: "john.doe@example.com",
      dateOfBirth: "1995-06-15",
      gender: "Male",
    },
    education: {
      collegeName: "MIT",
      qualification: "B.Tech",
      department: "Computer Science",
      yearOfPassing: "2020",
      cgpa: "8.5",
      collegeEmail: "john.doe@mit.edu",
      percentage10th: "92%",
      percentage12th: "89%",
    },
    skills: {
      resumeLink: "https://example.com/resume.pdf",
      gitLink: "https://github.com/johndoe",
      linkedinLink: "https://linkedin.com/in/johndoe",
      portfolioLink: "https://johndoe.dev",
      skillsList: ["React", "Node.js", "TypeScript", "Python", "AWS"],
    },
  },
  {
    id: 2,
    name: "Alice Smith",
    email: "alice.smith@example.com",
    status: "pending",
    interviewStatus: "not_scheduled",
    assignedInterviewer: "Not Assigned",
    profilePhoto:
      "https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=150&h=150&fit=crop&crop=face",
    personalDetails: {
      firstName: "Alice",
      lastName: "Smith",
      mobileNo: "+1-555-0124",
      email: "alice.smith@example.com",
      dateOfBirth: "1997-03-22",
      gender: "Female",
    },
    education: {
      collegeName: "Stanford University",
      qualification: "M.Tech",
      department: "Software Engineering",
      yearOfPassing: "2022",
      cgpa: "9.1",
      collegeEmail: "alice.smith@stanford.edu",
      percentage10th: "95%",
      percentage12th: "93%",
    },
    skills: {
      resumeLink: "https://example.com/alice-resume.pdf",
      gitLink: "https://github.com/alicesmith",
      linkedinLink: "https://linkedin.com/in/alicesmith",
      portfolioLink: "https://alicesmith.dev",
      skillsList: ["Vue.js", "Django", "PostgreSQL", "Docker", "Kubernetes"],
    },
  },
  {
    id: 3,
    name: "Mike Johnson",
    email: "mike.johnson@example.com",
    status: "canceled",
    interviewStatus: "not_scheduled",
    assignedInterviewer: "David Brown",
    profilePhoto:
      "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop&crop=face",
    personalDetails: {
      firstName: "Mike",
      lastName: "Johnson",
      mobileNo: "+1-555-0125",
      email: "mike.johnson@example.com",
      dateOfBirth: "1994-11-08",
      gender: "Male",
    },
    education: {
      collegeName: "UC Berkeley",
      qualification: "B.Tech",
      department: "Information Technology",
      yearOfPassing: "2018",
      cgpa: "7.8",
      collegeEmail: "mike.johnson@berkeley.edu",
      percentage10th: "88%",
      percentage12th: "85%",
    },
    skills: {
      resumeLink: "https://example.com/mike-resume.pdf",
      gitLink: "https://github.com/mikejohnson",
      linkedinLink: "https://linkedin.com/in/mikejohnson",
      portfolioLink: "https://mikejohnson.dev",
      skillsList: ["Angular", "Spring Boot", "MySQL", "Jenkins", "Git"],
    },
  },
  {
    id: 4,
    name: "Sophia Lee",
    email: "sophia.lee@example.com",
    status: "approved",
    interviewStatus: "scheduled",
    assignedInterviewer: "Emma Clark",
    profilePhoto:
      "https://images.unsplash.com/photo-1544723795-3fb6469f5b39?w=150&h=150&fit=crop&crop=face",
    personalDetails: {
      firstName: "Sophia",
      lastName: "Lee",
      mobileNo: "+1-555-0126",
      email: "sophia.lee@example.com",
      dateOfBirth: "1996-02-10",
      gender: "Female",
    },
    education: {
      collegeName: "Harvard University",
      qualification: "B.Sc",
      department: "AI & Data Science",
      yearOfPassing: "2021",
      cgpa: "9.3",
      collegeEmail: "sophia.lee@harvard.edu",
      percentage10th: "96%",
      percentage12th: "94%",
    },
    skills: {
      resumeLink: "https://example.com/sophia-resume.pdf",
      gitLink: "https://github.com/sophialee",
      linkedinLink: "https://linkedin.com/in/sophialee",
      portfolioLink: "https://sophialee.dev",
      skillsList: ["Python", "TensorFlow", "Pandas", "NLP", "Azure"],
    },
  },
  {
    id: 5,
    name: "David Kim",
    email: "david.kim@example.com",
    status: "pending",
    interviewStatus: "not_scheduled",
    assignedInterviewer: "Not Assigned",
    profilePhoto:
      "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&h=150&fit=crop&crop=face",
    personalDetails: {
      firstName: "David",
      lastName: "Kim",
      mobileNo: "+1-555-0127",
      email: "david.kim@example.com",
      dateOfBirth: "1998-09-05",
      gender: "Male",
    },
    education: {
      collegeName: "Carnegie Mellon",
      qualification: "M.Sc",
      department: "Cybersecurity",
      yearOfPassing: "2023",
      cgpa: "8.9",
      collegeEmail: "david.kim@cmu.edu",
      percentage10th: "91%",
      percentage12th: "90%",
    },
    skills: {
      resumeLink: "https://example.com/david-resume.pdf",
      gitLink: "https://github.com/davidkim",
      linkedinLink: "https://linkedin.com/in/davidkim",
      portfolioLink: "https://davidkim.dev",
      skillsList: ["C++", "Cybersecurity", "Ethical Hacking", "Linux", "AWS"],
    },
  },
  {
    id: 6,
    name: "Emma Brown",
    email: "emma.brown@example.com",
    status: "approved",
    interviewStatus: "scheduled",
    assignedInterviewer: "James Miller",
    profilePhoto:
      "https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=150&h=150&fit=crop&crop=face",
    personalDetails: {
      firstName: "Emma",
      lastName: "Brown",
      mobileNo: "+1-555-0128",
      email: "emma.brown@example.com",
      dateOfBirth: "1996-07-18",
      gender: "Female",
    },
    education: {
      collegeName: "Oxford University",
      qualification: "B.Tech",
      department: "Electronics",
      yearOfPassing: "2019",
      cgpa: "8.2",
      collegeEmail: "emma.brown@oxford.edu",
      percentage10th: "89%",
      percentage12th: "87%",
    },
    skills: {
      resumeLink: "https://example.com/emma-resume.pdf",
      gitLink: "https://github.com/emmabrown",
      linkedinLink: "https://linkedin.com/in/emmabrown",
      portfolioLink: "https://emmabrown.dev",
      skillsList: ["Embedded C", "IoT", "MATLAB", "FPGA", "Python"],
    },
  },
  {
    id: 7,
    name: "James Wilson",
    email: "james.wilson@example.com",
    status: "canceled",
    interviewStatus: "not_scheduled",
    assignedInterviewer: "Not Assigned",
    profilePhoto:
      "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&h=150&fit=crop&crop=face",
    personalDetails: {
      firstName: "James",
      lastName: "Wilson",
      mobileNo: "+1-555-0129",
      email: "james.wilson@example.com",
      dateOfBirth: "1993-12-11",
      gender: "Male",
    },
    education: {
      collegeName: "University of Toronto",
      qualification: "B.Sc",
      department: "Software Systems",
      yearOfPassing: "2017",
      cgpa: "7.6",
      collegeEmail: "james.wilson@utoronto.edu",
      percentage10th: "86%",
      percentage12th: "83%",
    },
    skills: {
      resumeLink: "https://example.com/james-resume.pdf",
      gitLink: "https://github.com/jameswilson",
      linkedinLink: "https://linkedin.com/in/jameswilson",
      portfolioLink: "https://jameswilson.dev",
      skillsList: ["Java", "Spring", "Hibernate", "SQL", "Docker"],
    },
  },
  {
    id: 8,
    name: "Olivia Martinez",
    email: "olivia.martinez@example.com",
    status: "approved",
    interviewStatus: "scheduled",
    assignedInterviewer: "Michael Scott",
    profilePhoto:
      "https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=150&h=150&fit=crop&crop=face",
    personalDetails: {
      firstName: "Olivia",
      lastName: "Martinez",
      mobileNo: "+1-555-0130",
      email: "olivia.martinez@example.com",
      dateOfBirth: "1999-05-27",
      gender: "Female",
    },
    education: {
      collegeName: "Yale University",
      qualification: "B.Tech",
      department: "Information Security",
      yearOfPassing: "2022",
      cgpa: "9.0",
      collegeEmail: "olivia.martinez@yale.edu",
      percentage10th: "94%",
      percentage12th: "92%",
    },
    skills: {
      resumeLink: "https://example.com/olivia-resume.pdf",
      gitLink: "https://github.com/oliviamartinez",
      linkedinLink: "https://linkedin.com/in/oliviamartinez",
      portfolioLink: "https://oliviamartinez.dev",
      skillsList: ["Go", "Kubernetes", "Prometheus", "Grafana", "Cloud"],
    },
  },
  {
    id: 9,
    name: "Liam Anderson",
    email: "liam.anderson@example.com",
    status: "pending",
    interviewStatus: "not_scheduled",
    assignedInterviewer: "Not Assigned",
    profilePhoto:
      "https://images.unsplash.com/photo-1527980965255-d3b416303d12?w=150&h=150&fit=crop&crop=face",
    personalDetails: {
      firstName: "Liam",
      lastName: "Anderson",
      mobileNo: "+1-555-0131",
      email: "liam.anderson@example.com",
      dateOfBirth: "1997-10-03",
      gender: "Male",
    },
    education: {
      collegeName: "University of Washington",
      qualification: "M.Tech",
      department: "Cloud Computing",
      yearOfPassing: "2023",
      cgpa: "9.2",
      collegeEmail: "liam.anderson@uw.edu",
      percentage10th: "93%",
      percentage12th: "90%",
    },
    skills: {
      resumeLink: "https://example.com/liam-resume.pdf",
      gitLink: "https://github.com/liamanderson",
      linkedinLink: "https://linkedin.com/in/liamanderson",
      portfolioLink: "https://liamanderson.dev",
      skillsList: ["AWS", "Terraform", "CI/CD", "Python", "Node.js"],
    },
  },
  {
    id: 10,
    name: "Ava Thompson",
    email: "ava.thompson@example.com",
    status: "approved",
    interviewStatus: "scheduled",
    assignedInterviewer: "Rachel Adams",
    profilePhoto:
      "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=150&h=150&fit=crop&crop=face",
    personalDetails: {
      firstName: "Ava",
      lastName: "Thompson",
      mobileNo: "+1-555-0132",
      email: "ava.thompson@example.com",
      dateOfBirth: "1998-01-19",
      gender: "Female",
    },
    education: {
      collegeName: "Princeton University",
      qualification: "B.Tech",
      department: "Machine Learning",
      yearOfPassing: "2020",
      cgpa: "8.7",
      collegeEmail: "ava.thompson@princeton.edu",
      percentage10th: "90%",
      percentage12th: "88%",
    },
    skills: {
      resumeLink: "https://example.com/ava-resume.pdf",
      gitLink: "https://github.com/avathompson",
      linkedinLink: "https://linkedin.com/in/avathompson",
      portfolioLink: "https://avathompson.dev",
      skillsList: ["Python", "Deep Learning", "NLP", "Pytorch", "Flask"],
    },
  },
];



export const upcomingInterviews = [
    {
      id: 1,
      candidateName: "Sarah Johnson",
      interviewerName: "John Smith",
      date: "2025-08-25",
      time: "10:00 AM",
      status: "Scheduled",
    },
    {
      id: 2,
      candidateName: "Michael Chen",
      interviewerName: "Emily Davis",
      date: "2025-08-25",
      time: "2:30 PM",
      status: "Scheduled",
    },
    {
      id: 3,
      candidateName: "Alex Rodriguez",
      interviewerName: "David Wilson",
      date: "2025-08-26",
      time: "11:00 AM",
      status: "Pending",
    },
    {
      id: 4,
      candidateName: "Lisa Thompson",
      interviewerName: "Jennifer Brown",
      date: "2025-08-26",
      time: "3:00 PM",
      status: "Scheduled",
    },
    {
      id: 5,
      candidateName: "Robert Garcia",
      interviewerName: "Mark Johnson",
      date: "2025-08-27",
      time: "9:30 AM",
      status: "Scheduled",
    },
    {
      id: 6,
      candidateName: "Lisa Thompson",
      interviewerName: "Jennifer Brown",
      date: "2025-08-26",
      time: "3:00 PM",
      status: "Scheduled",
    },
    {
      id: 7,
      candidateName: "Robert Garcia",
      interviewerName: "Mark Johnson",
      date: "2025-08-27",
      time: "9:30 AM",
      status: "Scheduled",
    },
  ];

export const interviewers = [
  {
    id: "1",
    name: "Robert Brown",
    email: "robert.brown@company.com",
    phone: "+1 (555) 123-4567",
    gender: "Male",
    yearsOfExperience: 8,
    role: "Technical Lead",
    department: "Engineering",
    status: "Active",
    profileImage:
      "https://img.freepik.com/premium-photo/happy-man-ai-generated-portrait-user-profile_1119669-1.jpg?w=2000",
    stats: {
      totalInterviews: 145,
      completedInterviews: 142,
      pendingInterviews: 3,
      totalHires: 23,
    },
  },
  {
    id: "2",
    name: "Lisa Wang",
    email: "lisa.wang@company.com",
    phone: "+1 (555) 234-5678",
    gender: "Female",
    yearsOfExperience: 6,
    role: "Senior Developer",
    department: "Engineering",
    status: "Active",
    profileImage:
      "https://img.freepik.com/premium-photo/portrait-cheerful-asian-woman_144627-58061.jpg?w=2000",
    stats: {
      totalInterviews: 89,
      completedInterviews: 85,
      pendingInterviews: 4,
      totalHires: 15,
    },
  },
  {
    id: "3",
    name: "John Smith",
    email: "john.smith@company.com",
    phone: "+1 (555) 345-6789",
    gender: "Male",
    yearsOfExperience: 12,
    role: "HR Specialist",
    department: "Human Resources",
    status: "Inactive",
    profileImage:
      "https://img.freepik.com/free-photo/portrait-happy-mature-man_23-2148206449.jpg?w=2000",
    stats: {
      totalInterviews: 230,
      completedInterviews: 225,
      pendingInterviews: 5,
      totalHires: 45,
    },
  },
  {
    id: "4",
    name: "Sarah Johnson",
    email: "sarah.johnson@company.com",
    phone: "+1 (555) 456-7890",
    gender: "Female",
    yearsOfExperience: 10,
    role: "Senior Manager",
    department: "Product",
    status: "Active",
    profileImage:
      "https://img.freepik.com/free-photo/portrait-beautiful-smiling-woman_171337-5058.jpg?w=2000",
    stats: {
      totalInterviews: 167,
      completedInterviews: 160,
      pendingInterviews: 7,
      totalHires: 28,
    },
  },
  {
    id: "5",
    name: "Michael Chen",
    email: "michael.chen@company.com",
    phone: "+1 (555) 567-8901",
    gender: "Male",
    yearsOfExperience: 7,
    role: "Senior Developer",
    department: "Design",
    status: "Inactive",
    profileImage:
      "https://img.freepik.com/free-photo/smiling-man-posing-studio_23-2148191223.jpg?w=2000",
    stats: {
      totalInterviews: 98,
      completedInterviews: 94,
      pendingInterviews: 4,
      totalHires: 18,
    },
  },
  {
    id: "6",
    name: "Emily Davis",
    email: "emily.davis@company.com",
    phone: "+1 (555) 678-9012",
    gender: "Female",
    yearsOfExperience: 9,
    role: "Technical Lead",
    department: "Engineering",
    status: "Active",
    profileImage:
      "https://img.freepik.com/free-photo/portrait-happy-young-woman_171337-5053.jpg?w=2000",
    stats: {
      totalInterviews: 110,
      completedInterviews: 108,
      pendingInterviews: 2,
      totalHires: 20,
    },
  },
  {
    id: "7",
    name: "David Lee",
    email: "david.lee@company.com",
    phone: "+1 (555) 789-0123",
    gender: "Male",
    yearsOfExperience: 11,
    role: "Senior Manager",
    department: "Product",
    status: "Inactive",
    profileImage:
      "https://img.freepik.com/free-photo/portrait-handsome-young-man_171337-5055.jpg?w=2000",
    stats: {
      totalInterviews: 130,
      completedInterviews: 127,
      pendingInterviews: 3,
      totalHires: 25,
    },
  },
  {
    id: "8",
    name: "Sophia Miller",
    email: "sophia.miller@company.com",
    phone: "+1 (555) 890-1234",
    gender: "Female",
    yearsOfExperience: 5,
    role: "HR Specialist",
    department: "Human Resources",
    status: "Active",
    profileImage:
      "https://img.freepik.com/free-photo/portrait-confident-businesswoman_23-2148232187.jpg?w=2000",
    stats: {
      totalInterviews: 75,
      completedInterviews: 73,
      pendingInterviews: 2,
      totalHires: 12,
    },
  },
  {
    id: "9",
    name: "Daniel Garcia",
    email: "daniel.garcia@company.com",
    phone: "+1 (555) 901-2345",
    gender: "Male",
    yearsOfExperience: 13,
    role: "Technical Lead",
    department: "Engineering",
    status: "Active",
    profileImage:
      "https://img.freepik.com/free-photo/smiling-mature-businessman_171337-5054.jpg?w=2000",
    stats: {
      totalInterviews: 150,
      completedInterviews: 145,
      pendingInterviews: 5,
      totalHires: 30,
    },
  },
  {
    id: "10",
    name: "Olivia Martinez",
    email: "olivia.martinez@company.com",
    phone: "+1 (555) 012-3456",
    gender: "Female",
    yearsOfExperience: 4,
    role: "Senior Developer",
    department: "Design",
    status: "Inactive",
    profileImage:
      "https://img.freepik.com/free-photo/portrait-happy-young-woman_171337-5056.jpg?w=2000",
    stats: {
      totalInterviews: 40,
      completedInterviews: 38,
      pendingInterviews: 2,
      totalHires: 6,
    },
  },
  {
    id: "11",
    name: "James Wilson",
    email: "james.wilson@company.com",
    phone: "+1 (555) 111-2222",
    gender: "Male",
    yearsOfExperience: 14,
    role: "Senior Manager",
    department: "Product",
    status: "Active",
    profileImage:
      "https://img.freepik.com/free-photo/portrait-happy-man-with-beard_171337-5057.jpg?w=2000",
    stats: {
      totalInterviews: 200,
      completedInterviews: 195,
      pendingInterviews: 5,
      totalHires: 50,
    },
  },
];
